---

- name: Install the Tigera Operator
  shell: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml

- name: Copy custom-resources.yaml
  template:
    src: custom-resources.j2
    dest: /tmp/custom-resources.yaml

- name: Install Calico
  shell: kubectl apply -f /tmp/custom-resources.yaml

- name: Delete custom-resources file
  file:
    path: /tmp/custom-resources.yaml
    state: absent
