---

- name: Get join command from master
  delegate_to: "{{ groups['master'][0] }}"
  command: kubeadm token create --print-join-command
  register: join_command

- name: print output join command
  debug:
    msg: "{{ join_command.stdout }}"

- name: execute join command
  become: yes
  command: "{{ join_command.stdout }}"
